### Get the users array
GET  http://localhost:8123/authentication/api/users

### Create a new user, 'fishingfreak'
POST http://localhost:8123/authentication/api/users
Content-Type: application/json

{
    "username": "fishingfreak",
    "password": "ilovefishing123",
    "email": "fishingfreak@gmail.com"
}

### Create a new user, 'runnerman'
POST http://localhost:8123/authentication/api/users
Content-Type: application/json

{
    "username": "runnerman",
    "password": "rU/\/everyDay!",
    "email": "runeveryday@gmail.com"
}


### Login a user
POST http://localhost:8123/authentication/api/sessions
Content-Type: application/json

{
    "username": "fishingfreak",
    "password": "ilovefishing123"
}

### Get the currently logged in user
GET http://localhost:8123/authentication/api/sessions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpc2hpbmdmcmVhayIsImVtYWlsIjoiZmlzaGluZ2ZyZWFrQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGlQR0U0emhyaXVFOWhlcHpBUXJhdE9JMkZveURSV0NQMmNYRTI2T0JFYUNOVEtXQXBGRTdhIiwiaWF0IjoxNjc2OTE5MTc3fQ.Pj_TwEUCeh-ROZcopPUF-1-G38w2aJ15Ba44hUsxto0