# JS5-P6-AUTHENTICATION

### Get the users array
GET  http://localhost:8123/authentication/api/users

// the c0d3 api returns error: not logged in, so we need middleware?

### Create a new user, 'fishingfreak'
POST http://localhost:8123/authentication/api/users
Content-Type: application/json

{
    "username": "fishingfreak",
    "password": "ilovefishing123",
    "email": "fishingfreak@gmail.com"
}

### Create a new user, 'runnerman'
POST http://localhost:8123/authentication/api/users
Content-Type: application/json

{
    "username": "runnerman",
    "password": "rU/\/everyDay!",
    "email": "runeveryday@gmail.com",
    "favorite food": "bananas",
    "average pace": "10mph"
}

### Login a user
POST http://localhost:8123/authentication/api/sessions
Content-Type: application/json

{
    "username": "fishingfreak",
    "password": "ilovefishing123"
}

### Get the currently logged in user
GET http://localhost:8123/authentication/api/sessions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpc2hpbmdmcmVhayIsImlhdCI6MTY3Njk1Njg4MH0.s14q7r677wfPX5FKGeymTUqgrzf_SprHWiOx4TMx-Q4

### C0D3 API - get all users
GET https://js5.c0d3.com/auth/api/sessions

# { "error": { "message": "not logged in" } }

# {
#   "username": "robot9",
#   "email": "@",
#   "id": "26038bd5-e570-4826-8647-b08ba06726e3",
#   "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvYm90OSIsImlhdCI6MTY3NjkxOTk3M30.kuf1SyYgo_uCmiGBgKyPLinwUbPm8YLdedsqZ4tY_fI"
# }

### C0D3 API - login a user
POST https://js5.c0d3.com/auth/api/sessions
Content-Type: application/json

{
    "username": "robot4",
    "password": "cm9ib3Q0"
}

# {
#   "username": "robot4",
#   "name": "robot robot",
#   "email": "robot4@robot.com",
#   "id": "df87b591-59af-4166-bca7-50ebdc101fdf",
#   "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvYm90NCIsImlhdCI6MTY3NjkyODY5N30.MAvY7-g1sq2McJLAelVj0u6iZ4s4udpbtFso71ksxs4"
# }

###
GET  https://js5.c0d3.com/auth/api/users
# { "users": [ ... contains one object per user ... ]}
# each user object has a "username", "email", "name", "password", "id", and sometimes a "jwt"
# some user objects also have an age field

### 
POST  https://js5.c0d3.com/auth/api/users
Content-Type: application/json

{
    "password": "robot10",
    "username": "robot10",
    "email": "robot10@"
}

# 400 Bad Requests
# { "error": { "message": "password field cannot be empty and must be base 64 encoded with more than 5 characters" } }

# { "error": { "message": "username field cannot be blank and must contain alpha numeric characters only" } }

# { "error": { "message": "username is taken, please pick another" } }

# { "error": { "message": "email field cannot be blank and must be a valid email" } }

# user created successfully, status 200
# {
#   "username": "robot9",
#   "email": "@",
#   "id": "26038bd5-e570-4826-8647-b08ba06726e3",
#   "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvYm90OSIsImlhdCI6MTY3NjkxOTk3M30.kuf1SyYgo_uCmiGBgKyPLinwUbPm8YLdedsqZ4tY_fI"
# }

### TEST - C0D3 API

# LOGIN THE USER
POST https://js5.c0d3.com/auth/api/sessions
Content-Type: application/json

{
    "username": "robot4",
    "password": "cm9ib3Q0"
}

###

GET  https://js5.c0d3.com/auth/api/sessions