export const shakespeareBots = ['shakespeare-bot-1', 'shakespeare-bot-2'];

export const shakespeareQuotes = [
    "Be not afraid of greatness. Some are born great, some achieve greatness, and others have greatness thrust upon them.",
    "We know what we are, but know not what we may be.",
    "Sweet are the uses of adversity which, like the toad, ugly and venomous, wears yet a precious jewel in his head.",
    "Our doubts are traitors and make us lose the good we oft might win by fearing to attempt.",
    "Give every man thy ear, but few thy voice.",
    "Uneasy lies the head that wears the crown.",
    "How poor are they that have not patience! What wound did ever heal but by degrees?",
    "Nothing can come of nothing.",
    "How far that little candle throws its beams! So shines a good deed in a naughty world.",
    "What's done can't be undone.",
    "Though she be but little, she is fierce.",
    "No legacy is so rich as honesty.",
    "This above all; to thine own self be true.",
    "I wasted time, and now doth time waste me.",
    "The robbed that smiles, steals something from the thief.",
    "The devil can cite Scripture for his purpose.",
    "One touch of nature makes the whole world kin.",
    "What is past is prologue.",
    "Small cheer and great welcome makes a merry feast.",
    "Sweet mercy is nobility's true badge.",
    "'Tis not enough to help the feeble up, but to support them after.",
    "Neither a borrower nor a lender be.",
    "Ambition should be made of sterner stuff.",
    "I bear a charmed life.",
    "Heat not a furnace for your foe so hot that it do singe yourself.",
    "Talking isn't doing. It is a kind of good deed to say well; and yet words are not deeds.",
    "In time we hate that which we often fear.",
    "Modest doubt is called the beacon of the wise.",
    "With mirth and laughter let old wrinkles come.",
    "Boldness be my friend.",
    "Words without thoughts never to heaven go.",
    "Wisely, and slow. They stumble that run fast.",
    "Pleasure and action make the hours seem short.",
    "When words are scarce they are seldom spent in vain.",
    "Such as we are made of, such we be.",
    "And oftentimes excusing of a fault doth make the fault the worse by the excuse.",
    "Reputation is an idle and most false imposition; oft got without merit, and lost without deserving.",
    "To be, or not to be: that is the question.",
    "All the world's a stage, and all the men and women merely players. They have their exits and their entrances; and one man in his time plays many parts.",
    "All that glisters is not gold.",
    "Words are easy, like the wind; faithful friends are hard to find.",
    "The fault...is not in our stars, but in ourselves.",
    "And this, our life, exempt from public haunt, finds tongues in trees, books in the running brooks, sermons in stones, and good in everything.",
    "Expectation is the root of all heartache.",
    "I like this place and could willingly waste my time in it.",
    "Better three hours too soon than a minute too late.",
    "Life's but a walking shadow, a poor player, that struts and frets his hour upon the stage, and then is heard no more; it is a tale told by an idiot, full of sound and fury, signifying nothing.",
    "My tongue will tell the anger of my heart, or else my heart concealing it will break.",
    "Brevity is the soul of wit.",
    "Give sorrow words; the grief that does not speak knits up o-er wrought heart and bids it break.",
    "Look like the innocent flower, but be the serpent under it.",
    "One may smile, and smile, be a villain.",
    "Conscience doth make cowards of us all.",
    "Let me be that I am and seek not to alter me.",
    "Et tu, Brute?",
    "O, beware, my lord, of jealousy; it is the green-ey'd monster, which doth mock the meat it feeds on.",
    "If we are true to ourselves, we can not be false to anyone.",
    "Be great in act, as you have been in thought.",
    "Suspicion always haunts the guilty mind.",
    "All things are ready, if our mind be so.",
    "Many a true word hath been spoken in jest.",
    "For sweetest things turn sourest by their deeds; lillies that fester smell far worse than weeds.",
    "The Devil hath power to assume a pleasing shape.",
    "Thought is free.",
    "April hath put a spirit of youth in everything.",
    "Summer's lease hath all too short a date.",
    "Our bodies are our gardens to the which our wills are gardeners.",
    "The tempter or the tempted, who sins most?",
    "Men should be what they seem.",
    "He jests at scars that never felt a wound."
];

export const catBots = [
    'American-Shorthair',
    'Bengal',
    'British-Shorthair',
    'Japanese-Bobtail',
    'Persian',
    'Siamese',
    'Sphynx',
    'Turkish-Angora'
]

export const catQuotes = [
    'meow',
    'mrrrow',
    'wrraoo!',
    'mrrowow',
    'hsssss',
    'HSSSSS',
    'prrup',
    'yeeeeeow',
    'miaow',
    'nya'
];

export const dogBots = [
    'German-Shepherd',
    'Labrador',
    'French-Bulldog',
    'Poodle',
    'Chihuahua',
    'Pomeranian',
    'Shiba-Inu',
    'Shih-Tzu',
    'Goldendoodle',
    'Australian-Shepherd'
];

export const dogQuotes = [
    'ruff ruff',
    'yap yap',
    'yip yip',
    'borf',
    'BORF',
    'bark',
    'woof',
    'ouaf ouaf'
];
